apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: if9t67kha-go 
  janus-idp.io/tekton: if9t67kha-go
  backstage.io/kubernetes-id: if9t67kha-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: if9t67kha-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  